FROM node:12 
# (자신이 생성할 이미지의 기반이 될 이미지 뒤에 숫자는 버전을 뜻함)

WORKDIR /app 
# ( 작업폴더 생성 앞으로 실행될 명령어들이 /app폴더에서 실행됨. mkdir app한 후에 cd app한 것과 동일 )


COPY . .
# (내 컴퓨터에 있는 소스코드,package.json등의 파일 또는 디렉토리를 이미지에 복사. )
# (위에 코드에서는 backend는 파일 및 디렉토리, ./ 는 복사할 경로를 나타냄)
# ( node_modules 폴더가 같이 복사되지 않도록 backend 폴더 안에 .dockerignore 라는 파일을 생성(.gitignore 파일과 동일) )

RUN npm install
# (이미지가 생성될 때 실행될 커맨드. 의존성파일들을 설치함)

EXPOSE 4000
# (컨테이너가 실행될 포트 설정...? 그냥 소스코드 내의 포트를 가져다 적으셈)

CMD ["node","src/index.js"]
# (이미지가 다 생성된 후 컨테이너를 실행할 때 쓰이는 커맨드)